#!/usr/bin/perl

use strict;
use warnings;
use lib "modules";
use Getopt::Long;

use AuthFile qw(create_auth_file);
use YamlConfig qw(create_yaml_config generate_mount_command);

my $yaml_file;
my $mount_flag = 0;
my $auth_flag = 0;
my $create_flag = 0;
my $help_flag = 0;

GetOptions(
    'a' => \$mount_flag,
    'p' => \$auth_flag,
    'c' => \$create_flag,         
    'file=s' => \$yaml_file,
    'help' => \$help_flag,    
) or die "Invalid options passed to $0\n";

if ($mount_flag) {
    generate_mount_command($yaml_file);
}

if ($auth_flag) {
    create_auth_file($yaml_file);
}

if ($create_flag) {
    create_yaml_config();
}

if ($help_flag) {
    my $help = <<END_MESSAGE;
    -a  Create configuration files for the connection.
    -p  Create a file with credentials for connecting to a network resource (for SMB).
    -c  Create a YAML configuration file.
    -f|--file=<filename>  Specify the YAML file to use.
    -h|--help  Display this help message.
END_MESSAGE
    print($help);
    exit 0;
}
